name: "Pipeline Juice Shop"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # 1. Llamamos al Reusable Workflow (Módulo 3)
  ci-build:
    uses: ./.github/workflows/reusable-build.yml

  # 2. Job de Seguridad Independiente
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm audit --audit-level=critical || true
      - run: npm audit --json > audit-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.json

  # 3. Construcción del Contenedor
  docker:
    needs: [ci-build, security] # Espera a la plantilla y a seguridad
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:latest

  # 4. Despliegue a Staging (Solo Develop)
  deploy-staging:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: "Deploy a Staging"
        run: |
          curl -s -X POST "${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}"
          echo "Staging desplegado"
  notify-staging:
    needs: deploy-staging
    if: always() && github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/reusable-notify.yml
    with:
      entorno: "Staging"
      estado: ${{ needs.deploy-staging.result }}
    secrets: inherit

# 5. Despliegue a Producción (Versión estándar)
  deploy-production:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: "Deploy a Producción"
        run: |
          curl -s -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          echo "Producción desplegada"
  
  notify-production:
    needs: deploy-production
    if: always() && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-notify.yml
    with:
      entorno: "Producción"
      estado: ${{ needs.deploy-production.result }}
    secrets: inherit