name: "Visible Name: Pipeline CI/CD"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Descargar código"
        uses: actions/checkout@v3
      
      - name: "Configurar Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          #cache: "npm"
      
      - name: "Instalar dependencias"
        #run: npm ci
        run: npm install
      
      #- name: "Ejecutar pruebas"
      #  run: npm test || true # "Demoraba mucho" exit code por credenciales externas
      
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - name: "Escanear vulnerabilidades"
        run: npm audit --audit-level=critical || true
      - name: "Guardar reporte"
        run: npm audit --json > audit-report.json || true
      - name: "Subir reporte como artefacto"
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.json

  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Solo ejecutar en main

    steps:
      - name: "Descargar código"
        uses: actions/checkout@v3

      - name: "Login en DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "Construir y publicar imagen"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:latest

  deploy-render:
    needs: docker-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Solo ejecutar en main

    steps:
      - name: "Desplegar en Render"
        run: |
          curl -s -X POST \
            "${{ secrets.RENDER_DEPLOY_HOOK }}" \
          && echo "Deploy disparado correctamente"
        